# EuRoC ROS config file 
# Store topic names 

left_camera_topic: /cam0/image_raw
right_camera_topic: /cam1/image_raw
imu_topic: /imu0
odometry_topic_name: /SparkVIO/GTSAM/odometry
reinit_topic: /SparkVIO/reinit
