# EuRoC ROS config file 
# Store topic names 

left_camera_topic: /mynteye/left/image_raw
right_camera_topic: /mynteye/left/image_raw
imu_topic: /mynteye/imu/data_raw
odometry_topic_name: /sparkvio/odometry
reinit_topic: /sparkvio/reinit
resiliency_topic_name: /sparkvio/resiliency
